name: Movie Deploy

on:
  push:
    branches: ["step1"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
        env:
          TMDB_API_BASE_URL: ${{ secrets.TMDB_API_BASE_URL }}
          TMDB_API_ACCESS_TOKEN: ${{ secrets.TMDB_API_ACCESS_TOKEN }}
          TMDB_IMAGE_BASE_URL: ${{ secrets.TMDB_IMAGE_BASE_URL }}

      - name: Upload pages artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: "./dist"

  deploy:
    needs: build_and_deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: "./dist"
      - name: Deploy to step1 branch
        run: |
          git config bxxmi
          git config bxxmi@gmail.com
          cp -r dist/* .
          git add -A
          git commit -m "Update build output"
          git push
